// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetData, GetResponses, GetRunsRunsByIdData, GetRunsRunsByIdErrors, GetRunsRunsByIdResponses, GetRunsRunsData, GetRunsRunsResponses, PostPlanPlanData, PostPlanPlanResponses, PostRunsPlanByIdRunData, PostRunsPlanByIdRunErrors, PostRunsPlanByIdRunResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({ url: '/', ...options });

export const postPlanPlan = <ThrowOnError extends boolean = false>(options: Options<PostPlanPlanData, ThrowOnError>) => (options.client ?? client).post<PostPlanPlanResponses, unknown, ThrowOnError>({
    url: '/plan/plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getRunsRuns = <ThrowOnError extends boolean = false>(options?: Options<GetRunsRunsData, ThrowOnError>) => (options?.client ?? client).get<GetRunsRunsResponses, unknown, ThrowOnError>({ url: '/runs/runs', ...options });

export const getRunsRunsById = <ThrowOnError extends boolean = false>(options: Options<GetRunsRunsByIdData, ThrowOnError>) => (options.client ?? client).get<GetRunsRunsByIdResponses, GetRunsRunsByIdErrors, ThrowOnError>({ url: '/runs/runs/{id}', ...options });

export const postRunsPlanByIdRun = <ThrowOnError extends boolean = false>(options: Options<PostRunsPlanByIdRunData, ThrowOnError>) => (options.client ?? client).post<PostRunsPlanByIdRunResponses, PostRunsPlanByIdRunErrors, ThrowOnError>({ url: '/runs/plan/{id}/run', ...options });
