// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostPlanPlanData = {
    body: {
        id: string;
        name: string;
        version: '1.0';
        endpoint_host: string;
        frequency?: {
            every: number;
            unit: 0 | 1 | 2;
        };
        nodes: Array<{
            id: string;
            data: {
                type: 0;
                method: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
                path: string;
                headers?: {
                    [key: string]: string;
                };
                body?: unknown;
                response_format: 0 | 1 | 2;
            } | {
                type: 1;
                duration_ms: number;
            } | {
                type: 2;
                assertions: Array<{
                    path: Array<string>;
                    predicate: 0 | 1 | 2 | 3 | {
                        expected: unknown;
                        operator: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
                    };
                } | {
                    path: Array<string>;
                    expected: unknown;
                } | {
                    path: string;
                    expected: unknown;
                }>;
            };
        }>;
        edges: Array<{
            from: string;
            to: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/plan/plan';
};

export type PostPlanPlanResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        name: string;
        version: '1.0';
        endpoint_host: string;
        frequency?: {
            every: number;
            unit: 0 | 1 | 2;
        };
        nodes: Array<{
            id: string;
            data: {
                type: 0;
                method: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
                path: string;
                headers?: {
                    [key: string]: string;
                };
                body?: unknown;
                response_format: 0 | 1 | 2;
            } | {
                type: 1;
                duration_ms: number;
            } | {
                type: 2;
                assertions: Array<{
                    path: Array<string>;
                    predicate: 0 | 1 | 2 | 3 | {
                        expected: unknown;
                        operator: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
                    };
                } | {
                    path: Array<string>;
                    expected: unknown;
                } | {
                    path: string;
                    expected: unknown;
                }>;
            };
        }>;
        edges: Array<{
            from: string;
            to: string;
        }>;
    };
};

export type PostPlanPlanResponse = PostPlanPlanResponses[keyof PostPlanPlanResponses];

export type GetRunsRunsData = {
    body?: never;
    path?: never;
    query?: {
        planId?: string;
        status?: 'pending' | 'running' | 'completed' | 'failed';
        limit?: number;
        offset?: number;
    };
    url: '/runs/runs';
};

export type GetRunsRunsResponses = {
    /**
     * Default Response
     */
    200: {
        runs: Array<{
            id: string;
            planId: string;
            planName: string;
            status: 'pending' | 'running' | 'completed' | 'failed';
            triggeredBy: 'schedule' | 'manual' | 'api';
            startedAt: string;
            completedAt?: string;
            duration_ms?: number;
            success?: boolean;
            errors?: Array<string>;
        }>;
        total: number;
        limit: number;
        offset: number;
    };
};

export type GetRunsRunsResponse = GetRunsRunsResponses[keyof GetRunsRunsResponses];

export type GetRunsRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/runs/{id}';
};

export type GetRunsRunsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetRunsRunsByIdError = GetRunsRunsByIdErrors[keyof GetRunsRunsByIdErrors];

export type GetRunsRunsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        planId: string;
        planName: string;
        status: 'pending' | 'running' | 'completed' | 'failed';
        triggeredBy: 'schedule' | 'manual' | 'api';
        startedAt: string;
        completedAt?: string;
        duration_ms?: number;
        success?: boolean;
        errors?: Array<string>;
    };
};

export type GetRunsRunsByIdResponse = GetRunsRunsByIdResponses[keyof GetRunsRunsByIdResponses];

export type PostRunsPlanByIdRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/plan/{id}/run';
};

export type PostRunsPlanByIdRunErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PostRunsPlanByIdRunError = PostRunsPlanByIdRunErrors[keyof PostRunsPlanByIdRunErrors];

export type PostRunsPlanByIdRunResponses = {
    /**
     * Default Response
     */
    200: {
        jobRun: {
            id: string;
            planId: string;
            planName: string;
            status: 'pending' | 'running' | 'completed' | 'failed';
            triggeredBy: 'schedule' | 'manual' | 'api';
            startedAt: string;
            completedAt?: string;
            duration_ms?: number;
            success?: boolean;
            errors?: Array<string>;
        };
        message: string;
    };
};

export type PostRunsPlanByIdRunResponse = PostRunsPlanByIdRunResponses[keyof PostRunsPlanByIdRunResponses];
