// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.js";
import type {
  DeleteAgentsByIdData,
  DeleteAgentsByIdResponses,
  DeletePlanByIdData,
  DeletePlanByIdErrors,
  DeletePlanByIdResponses,
  GetAgentsData,
  GetAgentsLocationsData,
  GetAgentsLocationsResponses,
  GetAgentsResponses,
  GetData,
  GetPlanByNameData,
  GetPlanByNameErrors,
  GetPlanByNameResponses,
  GetPlanData,
  GetPlanErrors,
  GetPlanResponses,
  GetResponses,
  GetRunsByIdData,
  GetRunsByIdErrors,
  GetRunsByIdResponses,
  GetRunsData,
  GetRunsErrors,
  GetRunsResponses,
  PatchRunsByIdData,
  PatchRunsByIdErrors,
  PatchRunsByIdResponses,
  PostAgentsByIdHeartbeatData,
  PostAgentsByIdHeartbeatErrors,
  PostAgentsByIdHeartbeatResponses,
  PostAgentsRegisterData,
  PostAgentsRegisterResponses,
  PostPlanData,
  PostPlanErrors,
  PostPlanResponses,
  PostRunsTriggerByPlanIdData,
  PostRunsTriggerByPlanIdErrors,
  PostRunsTriggerByPlanIdResponses,
  PutPlanByIdData,
  PutPlanByIdErrors,
  PutPlanByIdResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new GriffinHubSdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class GriffinHubSdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<GriffinHubSdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    GriffinHubSdk.__registry.set(this, args?.key);
  }

  public get<ThrowOnError extends boolean = false>(
    options?: Options<GetData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetResponses,
      unknown,
      ThrowOnError
    >({ url: "/", ...options });
  }

  /**
   * Register a new agent with the hub
   */
  public postAgentsRegister<ThrowOnError extends boolean = false>(
    options: Options<PostAgentsRegisterData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      PostAgentsRegisterResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/agents/register",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Record a heartbeat from an agent
   */
  public postAgentsByIdHeartbeat<ThrowOnError extends boolean = false>(
    options: Options<PostAgentsByIdHeartbeatData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      PostAgentsByIdHeartbeatResponses,
      PostAgentsByIdHeartbeatErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/agents/{id}/heartbeat",
      ...options,
    });
  }

  /**
   * Deregister an agent
   */
  public deleteAgentsById<ThrowOnError extends boolean = false>(
    options: Options<DeleteAgentsByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      DeleteAgentsByIdResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/agents/{id}",
      ...options,
    });
  }

  /**
   * List all agents with optional filtering
   */
  public getAgents<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentsData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetAgentsResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/agents/",
      ...options,
    });
  }

  /**
   * Get all registered locations (with at least one online agent)
   */
  public getAgentsLocations<ThrowOnError extends boolean = false>(
    options?: Options<GetAgentsLocationsData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetAgentsLocationsResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/agents/locations",
      ...options,
    });
  }

  public getPlan<ThrowOnError extends boolean = false>(
    options?: Options<GetPlanData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetPlanResponses,
      GetPlanErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/plan/",
      ...options,
    });
  }

  public postPlan<ThrowOnError extends boolean = false>(
    options: Options<PostPlanData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      PostPlanResponses,
      PostPlanErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/plan/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public deletePlanById<ThrowOnError extends boolean = false>(
    options: Options<DeletePlanByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      DeletePlanByIdResponses,
      DeletePlanByIdErrors,
      ThrowOnError
    >({ url: "/plan/{id}", ...options });
  }

  public putPlanById<ThrowOnError extends boolean = false>(
    options: Options<PutPlanByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      PutPlanByIdResponses,
      PutPlanByIdErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/plan/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public getPlanByName<ThrowOnError extends boolean = false>(
    options: Options<GetPlanByNameData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetPlanByNameResponses,
      GetPlanByNameErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/plan/by-name",
      ...options,
    });
  }

  public getRuns<ThrowOnError extends boolean = false>(
    options?: Options<GetRunsData, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetRunsResponses,
      GetRunsErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/runs/",
      ...options,
    });
  }

  public getRunsById<ThrowOnError extends boolean = false>(
    options: Options<GetRunsByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetRunsByIdResponses,
      GetRunsByIdErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/runs/{id}",
      ...options,
    });
  }

  public patchRunsById<ThrowOnError extends boolean = false>(
    options: Options<PatchRunsByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).patch<
      PatchRunsByIdResponses,
      PatchRunsByIdErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/runs/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public postRunsTriggerByPlanId<ThrowOnError extends boolean = false>(
    options: Options<PostRunsTriggerByPlanIdData, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      PostRunsTriggerByPlanIdResponses,
      PostRunsTriggerByPlanIdErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/runs/trigger/{planId}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
