// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3000' | (string & {});
};

/**
 * MonitorV1
 */
export type MonitorV1 = {
    project: string;
    locations?: Array<string>;
    id: string;
    name: string;
    /**
     * MonitorVersion
     */
    version: '1.0';
    /**
     * Frequency
     */
    frequency: {
        every: number;
        /**
         * FrequencyUnit
         */
        unit: 'MINUTE' | 'HOUR' | 'DAY';
    };
    environment: string;
    /**
     * Node
     */
    nodes: Array<{
        id: string;
        type: 'HTTP_REQUEST';
        /**
         * HttpMethod
         */
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE';
        path: string;
        base: string;
        headers?: {
            [key: string]: {
                $secret: {
                    provider: string;
                    ref: string;
                    version?: string;
                    field?: string;
                };
            } | {
                $literal: string;
            };
        };
        body?: unknown;
        /**
         * ResponseFormat
         */
        response_format: 'JSON' | 'XML';
    } | {
        id: string;
        type: 'WAIT';
        duration_ms: number;
    } | {
        id: string;
        type: 'ASSERTION';
        /**
         * Assertion
         */
        assertions: Array<{
            nodeId: string;
            subject: 'status';
            predicate: BinaryPredicate;
        } | {
            nodeId: string;
            subject: 'headers';
            headerName: string;
            predicate: UnaryPredicate | BinaryPredicate;
        } | {
            nodeId: string;
            subject: 'latency';
            predicate: BinaryPredicate;
        } | {
            nodeId: string;
            subject: 'body';
            responseType: 'JSON';
            path: Array<string>;
            predicate: UnaryPredicate | BinaryPredicate;
        } | {
            nodeId: string;
            subject: 'body';
            responseType: 'XML';
            path: Array<string>;
            predicate: UnaryPredicate | BinaryPredicate;
        }>;
    }>;
    edges: Array<{
        from: string;
        to: string;
    }>;
};

/**
 * MonitorVersion
 */
export type MonitorVersion = '1.0';

/**
 * Frequency
 */
export type Frequency = {
    every: number;
    /**
     * FrequencyUnit
     */
    unit: 'MINUTE' | 'HOUR' | 'DAY';
};

/**
 * FrequencyUnit
 */
export type FrequencyUnit = 'MINUTE' | 'HOUR' | 'DAY';

/**
 * Node
 */
export type Node = {
    id: string;
    type: 'HTTP_REQUEST';
    /**
     * HttpMethod
     */
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE';
    path: string;
    base: string;
    headers?: {
        [key: string]: {
            $secret: {
                provider: string;
                ref: string;
                version?: string;
                field?: string;
            };
        } | {
            $literal: string;
        };
    };
    body?: unknown;
    /**
     * ResponseFormat
     */
    response_format: 'JSON' | 'XML';
} | {
    id: string;
    type: 'WAIT';
    duration_ms: number;
} | {
    id: string;
    type: 'ASSERTION';
    /**
     * Assertion
     */
    assertions: Array<{
        nodeId: string;
        subject: 'status';
        predicate: BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'headers';
        headerName: string;
        predicate: UnaryPredicate | BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'latency';
        predicate: BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'body';
        responseType: 'JSON';
        path: Array<string>;
        predicate: UnaryPredicate | BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'body';
        responseType: 'XML';
        path: Array<string>;
        predicate: UnaryPredicate | BinaryPredicate;
    }>;
};

/**
 * HttpRequest
 */
export type HttpRequest = {
    id: string;
    type: 'HTTP_REQUEST';
    /**
     * HttpMethod
     */
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE';
    path: string;
    base: string;
    headers?: {
        [key: string]: {
            $secret: {
                provider: string;
                ref: string;
                version?: string;
                field?: string;
            };
        } | {
            $literal: string;
        };
    };
    body?: unknown;
    /**
     * ResponseFormat
     */
    response_format: 'JSON' | 'XML';
};

/**
 * HttpMethod
 */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE';

/**
 * SecretOrString
 */
export type SecretOrString = {
    $secret: {
        provider: string;
        ref: string;
        version?: string;
        field?: string;
    };
} | {
    $literal: string;
};

/**
 * SecretRef
 */
export type SecretRef = {
    $secret: {
        provider: string;
        ref: string;
        version?: string;
        field?: string;
    };
};

/**
 * StringLiteral
 */
export type StringLiteral = {
    $literal: string;
};

/**
 * ResponseFormat
 */
export type ResponseFormat = 'JSON' | 'XML';

/**
 * Wait
 */
export type Wait = {
    id: string;
    type: 'WAIT';
    duration_ms: number;
};

/**
 * Assertions
 */
export type Assertions = {
    id: string;
    type: 'ASSERTION';
    /**
     * Assertion
     */
    assertions: Array<{
        nodeId: string;
        subject: 'status';
        predicate: BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'headers';
        headerName: string;
        predicate: UnaryPredicate | BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'latency';
        predicate: BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'body';
        responseType: 'JSON';
        path: Array<string>;
        predicate: UnaryPredicate | BinaryPredicate;
    } | {
        nodeId: string;
        subject: 'body';
        responseType: 'XML';
        path: Array<string>;
        predicate: UnaryPredicate | BinaryPredicate;
    }>;
};

/**
 * Assertion
 */
export type Assertion = {
    nodeId: string;
    subject: 'status';
    predicate: BinaryPredicate;
} | {
    nodeId: string;
    subject: 'headers';
    headerName: string;
    predicate: UnaryPredicate | BinaryPredicate;
} | {
    nodeId: string;
    subject: 'latency';
    predicate: BinaryPredicate;
} | {
    nodeId: string;
    subject: 'body';
    responseType: 'JSON';
    path: Array<string>;
    predicate: UnaryPredicate | BinaryPredicate;
} | {
    nodeId: string;
    subject: 'body';
    responseType: 'XML';
    path: Array<string>;
    predicate: UnaryPredicate | BinaryPredicate;
};

/**
 * Edge
 */
export type Edge = {
    from: string;
    to: string;
};

/**
 * BinaryPredicate
 */
export type BinaryPredicate = {
    expected: unknown;
    operator: BinaryPredicateOperator;
    type: 'binary';
};

/**
 * BinaryPredicateOperator
 */
export type BinaryPredicateOperator = 'EQUAL' | 'NOT_EQUAL' | 'GREATER_THAN' | 'LESS_THAN' | 'GREATER_THAN_OR_EQUAL' | 'LESS_THAN_OR_EQUAL' | 'CONTAINS' | 'NOT_CONTAINS' | 'STARTS_WITH' | 'ENDS_WITH' | 'NOT_STARTS_WITH' | 'NOT_ENDS_WITH';

/**
 * UnaryPredicate
 */
export type UnaryPredicate = {
    operator: UnaryPredicateOperator;
    type: 'unary';
};

/**
 * UnaryPredicateOperator
 */
export type UnaryPredicateOperator = 'IS_NULL' | 'IS_NOT_NULL' | 'IS_TRUE' | 'IS_FALSE' | 'IS_EMPTY' | 'IS_NOT_EMPTY';

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostAgentsRegisterData = {
    body: {
        location: string;
        metadata?: {
            [key: string]: string;
        };
    };
    path?: never;
    query?: never;
    url: '/agents/register';
};

export type PostAgentsRegisterResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        location: string;
        /**
         * AgentStatus
         */
        status: 'online' | 'offline';
        lastHeartbeat: string;
        registeredAt: string;
        metadata?: {
            [key: string]: string;
        };
    };
};

export type PostAgentsRegisterResponse = PostAgentsRegisterResponses[keyof PostAgentsRegisterResponses];

export type PostAgentsByIdHeartbeatData = {
    body?: never;
    path: {
        /**
         * Agent ID
         */
        id: string;
    };
    query?: never;
    url: '/agents/{id}/heartbeat';
};

export type PostAgentsByIdHeartbeatErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PostAgentsByIdHeartbeatError = PostAgentsByIdHeartbeatErrors[keyof PostAgentsByIdHeartbeatErrors];

export type PostAgentsByIdHeartbeatResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type PostAgentsByIdHeartbeatResponse = PostAgentsByIdHeartbeatResponses[keyof PostAgentsByIdHeartbeatResponses];

export type DeleteAgentsByIdData = {
    body?: never;
    path: {
        /**
         * Agent ID
         */
        id: string;
    };
    query?: never;
    url: '/agents/{id}';
};

export type DeleteAgentsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteAgentsByIdResponse = DeleteAgentsByIdResponses[keyof DeleteAgentsByIdResponses];

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by location
         */
        location?: string;
        /**
         * Filter by status
         */
        status?: 'online' | 'offline';
    };
    url: '/agents/';
};

export type GetAgentsResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            id: string;
            location: string;
            status: 'online' | 'offline';
            lastHeartbeat: string;
            registeredAt: string;
            metadata?: {
                [key: string]: string;
            };
        }>;
        total: number;
    };
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type GetAgentsLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents/locations';
};

export type GetAgentsLocationsResponses = {
    /**
     * Default Response
     */
    200: {
        locations: Array<string>;
    };
};

export type GetAgentsLocationsResponse = GetAgentsLocationsResponses[keyof GetAgentsLocationsResponses];

export type GetMonitorData = {
    body?: never;
    path?: never;
    query?: {
        projectId?: string;
        environment?: string;
        limit?: number;
        offset?: number;
    };
    url: '/monitor/';
};

export type GetMonitorErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type GetMonitorError = GetMonitorErrors[keyof GetMonitorErrors];

export type GetMonitorResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<MonitorV1>;
        total: number;
        page: number;
        limit: number;
    };
};

export type GetMonitorResponse = GetMonitorResponses[keyof GetMonitorResponses];

export type PostMonitorData = {
    body: {
        project: string;
        locations?: Array<string>;
        name: string;
        version: '1.0';
        frequency: {
            every: number;
            unit: 'MINUTE' | 'HOUR' | 'DAY';
        };
        environment: string;
        nodes: Array<{
            id: string;
            type: 'HTTP_REQUEST';
            method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE';
            path: string;
            base: string;
            headers?: {
                [key: string]: {
                    $secret: {
                        provider: string;
                        ref: string;
                        version?: string;
                        field?: string;
                    };
                } | {
                    $literal: string;
                };
            };
            body?: unknown;
            response_format: 'JSON' | 'XML';
        } | {
            id: string;
            type: 'WAIT';
            duration_ms: number;
        } | {
            id: string;
            type: 'ASSERTION';
            assertions: Array<{
                nodeId: string;
                subject: 'status';
                predicate: BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'headers';
                headerName: string;
                predicate: UnaryPredicate | BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'latency';
                predicate: BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'body';
                responseType: 'JSON';
                path: Array<string>;
                predicate: UnaryPredicate | BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'body';
                responseType: 'XML';
                path: Array<string>;
                predicate: UnaryPredicate | BinaryPredicate;
            }>;
        }>;
        edges: Array<{
            from: string;
            to: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/monitor/';
};

export type PostMonitorErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type PostMonitorError = PostMonitorErrors[keyof PostMonitorErrors];

export type PostMonitorResponses = {
    /**
     * Default Response
     */
    201: {
        data: MonitorV1;
    };
};

export type PostMonitorResponse = PostMonitorResponses[keyof PostMonitorResponses];

export type DeleteMonitorByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/monitor/{id}';
};

export type DeleteMonitorByIdErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type DeleteMonitorByIdError = DeleteMonitorByIdErrors[keyof DeleteMonitorByIdErrors];

export type DeleteMonitorByIdResponses = {
    /**
     * Default Response
     */
    204: void;
};

export type DeleteMonitorByIdResponse = DeleteMonitorByIdResponses[keyof DeleteMonitorByIdResponses];

export type PutMonitorByIdData = {
    body: {
        project: string;
        locations?: Array<string>;
        name: string;
        version: '1.0';
        frequency: {
            every: number;
            unit: 'MINUTE' | 'HOUR' | 'DAY';
        };
        environment: string;
        nodes: Array<{
            id: string;
            type: 'HTTP_REQUEST';
            method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE';
            path: string;
            base: string;
            headers?: {
                [key: string]: {
                    $secret: {
                        provider: string;
                        ref: string;
                        version?: string;
                        field?: string;
                    };
                } | {
                    $literal: string;
                };
            };
            body?: unknown;
            response_format: 'JSON' | 'XML';
        } | {
            id: string;
            type: 'WAIT';
            duration_ms: number;
        } | {
            id: string;
            type: 'ASSERTION';
            assertions: Array<{
                nodeId: string;
                subject: 'status';
                predicate: BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'headers';
                headerName: string;
                predicate: UnaryPredicate | BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'latency';
                predicate: BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'body';
                responseType: 'JSON';
                path: Array<string>;
                predicate: UnaryPredicate | BinaryPredicate;
            } | {
                nodeId: string;
                subject: 'body';
                responseType: 'XML';
                path: Array<string>;
                predicate: UnaryPredicate | BinaryPredicate;
            }>;
        }>;
        edges: Array<{
            from: string;
            to: string;
        }>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/monitor/{id}';
};

export type PutMonitorByIdErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type PutMonitorByIdError = PutMonitorByIdErrors[keyof PutMonitorByIdErrors];

export type PutMonitorByIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: MonitorV1;
    };
};

export type PutMonitorByIdResponse = PutMonitorByIdResponses[keyof PutMonitorByIdResponses];

export type GetMonitorByNameData = {
    body?: never;
    path?: never;
    query: {
        projectId: string;
        environment: string;
        name: string;
        version?: 'latest' | string;
    };
    url: '/monitor/by-name';
};

export type GetMonitorByNameErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type GetMonitorByNameError = GetMonitorByNameErrors[keyof GetMonitorByNameErrors];

export type GetMonitorByNameResponses = {
    /**
     * Default Response
     */
    200: {
        data: MonitorV1;
    };
};

export type GetMonitorByNameResponse = GetMonitorByNameResponses[keyof GetMonitorByNameResponses];

export type GetRunsData = {
    body?: never;
    path?: never;
    query?: {
        monitorId?: string;
        /**
         * JobRunStatus
         */
        status?: 'pending' | 'running' | 'completed' | 'failed';
        limit?: number;
        offset?: number;
    };
    url: '/runs/';
};

export type GetRunsErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type GetRunsError = GetRunsErrors[keyof GetRunsErrors];

export type GetRunsResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            id: string;
            monitorId: string;
            executionGroupId: string;
            location: string;
            environment: string;
            status: 'pending' | 'running' | 'completed' | 'failed';
            /**
             * TriggerType
             */
            triggeredBy: 'schedule' | 'manual' | 'api';
            startedAt: string;
            completedAt?: string;
            duration_ms?: number;
            success?: boolean;
            errors?: Array<string>;
        }>;
        total: number;
        page: number;
        limit: number;
    };
};

export type GetRunsResponse = GetRunsResponses[keyof GetRunsResponses];

export type GetRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}';
};

export type GetRunsByIdErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type GetRunsByIdError = GetRunsByIdErrors[keyof GetRunsByIdErrors];

export type GetRunsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            monitorId: string;
            executionGroupId: string;
            location: string;
            environment: string;
            status: 'pending' | 'running' | 'completed' | 'failed';
            triggeredBy: 'schedule' | 'manual' | 'api';
            startedAt: string;
            completedAt?: string;
            duration_ms?: number;
            success?: boolean;
            errors?: Array<string>;
        };
    };
};

export type GetRunsByIdResponse = GetRunsByIdResponses[keyof GetRunsByIdResponses];

export type PatchRunsByIdData = {
    body?: {
        status?: 'pending' | 'running' | 'completed' | 'failed';
        completedAt?: string;
        duration_ms?: number;
        success?: boolean;
        errors?: Array<string>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/runs/{id}';
};

export type PatchRunsByIdErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type PatchRunsByIdError = PatchRunsByIdErrors[keyof PatchRunsByIdErrors];

export type PatchRunsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            monitorId: string;
            executionGroupId: string;
            location: string;
            environment: string;
            status: 'pending' | 'running' | 'completed' | 'failed';
            triggeredBy: 'schedule' | 'manual' | 'api';
            startedAt: string;
            completedAt?: string;
            duration_ms?: number;
            success?: boolean;
            errors?: Array<string>;
        };
    };
};

export type PatchRunsByIdResponse = PatchRunsByIdResponses[keyof PatchRunsByIdResponses];

export type PostRunsTriggerByMonitorIdData = {
    body: {
        environment: string;
    };
    path: {
        monitorId: string;
    };
    query?: never;
    url: '/runs/trigger/{monitorId}';
};

export type PostRunsTriggerByMonitorIdErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
    };
    /**
     * Default Response
     */
    401: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
    /**
     * Default Response
     */
    500: {
        error: string;
    };
    /**
     * Default Response
     */
    502: {
        error: string;
    };
    /**
     * Default Response
     */
    503: {
        error: string;
    };
    /**
     * Default Response
     */
    504: {
        error: string;
    };
};

export type PostRunsTriggerByMonitorIdError = PostRunsTriggerByMonitorIdErrors[keyof PostRunsTriggerByMonitorIdErrors];

export type PostRunsTriggerByMonitorIdResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            id: string;
            monitorId: string;
            executionGroupId: string;
            location: string;
            environment: string;
            status: 'pending' | 'running' | 'completed' | 'failed';
            triggeredBy: 'schedule' | 'manual' | 'api';
            startedAt: string;
            completedAt?: string;
            duration_ms?: number;
            success?: boolean;
            errors?: Array<string>;
        };
    };
};

export type PostRunsTriggerByMonitorIdResponse = PostRunsTriggerByMonitorIdResponses[keyof PostRunsTriggerByMonitorIdResponses];
